### PR TITLE
Draw bug

### PR DESCRIPTION
**Pull request by rohan20**
- Fixed win game logic
- Added comments for better readability

### CODE REVIEW

**Comment by till-tomorrow** [comment]
What was the bug? I am not able to figure out exactly.

**Comment by till-tomorrow** [comment]
Do I have to change misc.xml and workspace.xml only? Or should I upload my .idea for you to see?

**Comment by rohan20** [comment]
Let's consider the method where the user taps on box 1:

```
public void checkPlayer1Win() {
        if (!TextUtils.isEmpty(tv2.getText().toString()) && !TextUtils.isEmpty(tv3.getText().toString())) {
            if (tv2.getText().toString().equals(tv3.getText().toString()) && tv2.getText().toString().equals(tv1.getText().toString())) {
                checkWin= true;
                if (tv1.getText().toString().equals("O")){
                    Toast.makeText(PlayGame.this, "Player 2 won!!", Toast.LENGTH_SHORT).show(); //symbol O
                    displayAlertDialog();
                }
                else{
                    Toast.makeText(PlayGame.this, "Player 1 won!!", Toast.LENGTH_SHORT).show(); //symbol X
                    displayAlertDialog();
                }
            }
        } else if (!TextUtils.isEmpty(tv4.getText().toString()) && !TextUtils.isEmpty(tv7.getText().toString())) {
            if (tv4.getText().toString().equals(tv7.getText().toString()) && tv4.getText().toString().equals(tv1.getText().toString())) {
                checkWin= true;
                if (tv1.getText().toString().equals("O")){
                    Toast.makeText(PlayGame.this, "Player 2 won!!", Toast.LENGTH_SHORT).show(); //symbol O
                    displayAlertDialog();
                }

                else{
                    Toast.makeText(PlayGame.this, "Player 1 won!!", Toast.LENGTH_SHORT).show(); //symbol X
                    displayAlertDialog();
                }
            }
        } else if (!TextUtils.isEmpty(tv5.getText().toString()) && !TextUtils.isEmpty(tv9.getText().toString())) {
            if (tv5.getText().toString().equals(tv9.getText().toString()) && tv5.getText().toString().equals(tv1.getText().toString())) {
                checkWin= true;
                if (tv1.getText().toString().equals("O")){
                    Toast.makeText(PlayGame.this, "Player 2 won!!", Toast.LENGTH_SHORT).show(); //symbol O
                    displayAlertDialog();
                }
                else{
                    Toast.makeText(PlayGame.this, "Player 1 won!!", Toast.LENGTH_SHORT).show(); //symbol X
                    displayAlertDialog();
                }
            }
        }
    }
```

Here, the first if condition says that if box 2 and 3 are not empty then check if box 1, 2 and 3 have the same text or not.

If they do, your code would work fine.
But if they don't, your code wouldn't check for box 1,4,7 or box 1,5,9 since those two conditions are **else if** conditions and not **if** conditions.

**Comment by till-tomorrow** [comment]
This shouldn't have happened...:(

https://www.javatpoint.com/java-if-else
The above website also justifies my point.

**Pull request merged**
